#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S3,     HTSPB,          sensorI2CCustom9V)
#pragma config(Sensor, S4,     SMUX,           sensorI2CCustom)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     DRIVE_SE,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     DRIVE_NE,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     TUBE,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     FEEDER,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     POPPER,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_2,     FORK,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     DRIVE_SW,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C2_2,     DRIVE_NW,      tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S2_C3_1,    GRAB1,                tServoStandard)
#pragma config(Servo,  srvo_S2_C3_2,    GRAB2,                tServoStandard)
#pragma config(Servo,  srvo_S2_C3_3,    SPOUT,                tServoStandard)
#pragma config(Servo,  srvo_S2_C3_4,    ROOF,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C3_6,    FLAP,                 tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#ifdef USING_CLION
#include "../headers/clion_1.h"
#endif

#define DEBUG_IR
#define IR_SEEK_VAL HTIRSreadDir(msensor_S4_1)
#define GYRO_VAL HTIRSreadDir(msensor_S4_2)
#define GYRO_CAL HTIRSreadDir(msensor_S4_2)

#include "Joystickdriver.c"

#include "../drivers/hitechnic-sensormux.h"
#include "../drivers/hitechnic-irseeker-v1.h"
#include "../drivers/hitechnic-superpro.h"

#include "../headers/scaleJoy_1.h"
#include "../headers/gyro_1.h"
#include "../headers/nav_5.h"
#include "../headers/helpers_1.h"

//==================  Config Definitions  ==================
typedef enum
{
  kAllianceRed,
  kAllianceBlu
} Alliance_t;

typedef enum
{
  kPlanKick,
  kPlanRamp
} Plan_t;
#define DEF_PLAN_STRINGS const string Plan_s[] = {"Kick", "Ramp"};


#include "../headers/dialog_2.h"

void initialize_servos()
{
  servo[ROOF] = 255;
  servo[FLAP] = 25;
  servo[SPOUT] = 0;
}

//==================  Missions  ==================
void mission_monolith(Alliance_t alliance, int monolith_position)
{
  writeDebugStreamLine("%i", monolith_position);

  switch (monolith_position) {
  case 1:
    drive_enc(N, 30, 2500);
    drive_enc(CW, 70, 1100);
    drive_enc(N, 70, 3000);
    drive(S, -2, 1200);
    break;
  case 2:
    drive_enc(N, 55, 840);
    drive(FWD + 25, 55, 800);
    drive_enc(CW, 100, 1000);
    drive_enc(N, 100, 2800);
    drive(S, -2, 1200);
    break;
  case 3:
    drive_enc(W, 100, 1500);
    drive_enc(N, 55, 2600);
    drive(ACW, 70, 250);
    drive_enc(N, 55, 900);
    drive(CW, 40, 1400);
    drive_enc(N, 58, 2000);
    //drive(S, -20, 1800);
    break;
  }
}

void mission_ramp(Alliance_t alliance)
{
  drive(S, 40, 500);
  drive(N, 1, 1000);
  drive(S, 2, 500);
  drive(N, 1, 100);
  drive(S, 20, 900);
  drive(CCW, 40, 200);
  drive(S, 20, 200);
  drive(W, 100, 500);
  PlayImmediateTone(200,200);
  drive(S, 20, 1400);
//  drive(CCW, 40, 200);
  drive_enc(S, 15, 1300);

  motor[FORK] = 100;
  wait1Msec(1500);
  motor[FORK] = 0;

  motor[TUBE] = 100;
  wait1Msec(6200);
  motor[TUBE] = 0;

  servo[SPOUT] = 255;
  wait1Msec(1200);
  servo[ROOF] = 127;
  wait1Msec(500);
  servo[FLAP] = 80;

  motor[POPPER] = 100;
  wait1Msec(2000);
  motor[POPPER] = 0;
  /*
  motor[TUBE] = 100;
  while (HTSPBreadIO(HTSPB, 0x01) != 1) {}
  motor[TUBE] = 0;
  //  */
}

//==================  Main Task  ==================
task main()
{
  HTSPBsetupIO(HTSPB, 0x10);

  Alliance_t cur_alli = kAllianceRed;
  Plan_t cur_plan = kPlanRamp;
  int delay = 0;

  //dialog(&cur_alli, &cur_plan, &delay); // Run Dialog for user input of parameters

  initialize_servos();
  //  waitForStart();
  //  StartTask(updateBearing);

  wait1Msec(500);
  wait1Msec(delay * 1000);

  switch (cur_plan) {
  case kPlanRamp: //================== Plan Ramp
    mission_ramp(cur_alli);
    break;


  case kPlanKick: //================== Plan Kick
    int first_IR = IR_SEEK_VAL;
    drive_enc(N, 20, 2000);
    int second_IR = IR_SEEK_VAL; //157.56

    int monolith_position;
    if (first_IR <= 3) {
      monolith_position = 1;
      } else if (second_IR == 5) {
      monolith_position = 3;
      } else {
      monolith_position = 2;
    }
#ifdef DEBUG_IR
    writeDebugStreamLine("first: %i, second: %i", first_IR, second_IR);
    writeDebugStreamLine("result: %i", monolith_position);
    switch (monolith_position) {
    case 1:
      PlayImmediateTone(900, 300);
      break;
    case 2:
      PlayImmediateTone(650, 190);
      wait1Msec(100);
      PlayImmediateTone(650, 190);
      wait1Msec(10);
      break;
    case 3:
      PlayImmediateTone(400, 90);
      wait1Msec(10);
      PlayImmediateTone(400, 90);
      wait1Msec(10);
      PlayImmediateTone(400, 90);
      wait1Msec(10);
      break;
    }
    wait1Msec(2000);
#endif
    mission_monolith(cur_alli, monolith_position);
    drive_enc(CW, 80, 5000);
    /*
    servo[guides] = 255;
    wait1Msec(500);
    servo[guides] = 0;
    motor[TUBE] = 100;
    while (HTSPBreadIO(HTSPB, 0x01) != 1) {}*/
    motor[TUBE] = 0;
    break;
  }
  halt();

  //==================  Ending  ==================
  halt();
  PlayImmediateTone(200, 200);
  wait1Msec(1000);
}
