#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S3,     GYRO,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     IR_SEEK,        sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     DRIVE_SE,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     DRIVE_NE,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     LIFT,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     FEEDER,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     POPPER,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     DRIVE_SW,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     DRIVE_NW,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C3_1,    grab1,                tServoStandard)
#pragma config(Servo,  srvo_S2_C3_2,    grab2,                tServoStandard)
#pragma config(Servo,  srvo_S2_C3_3,    flip,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C3_4,    roof,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "../headers/scaleJoy_1.h"
#include "../headers/helpers_1.h"
#include "../headers/gyro_1.h"
#include "../headers/nav_5.h"

typedef enum {
	kAllianceRed,
	kAllianceBlu
} Alliance_t;

void mission_monolith(Alliance_t alliance, int monolith_position)
{
		writeDebugStreamLine("%i", monolith_position);

	switch (monolith_position) {
	case 1:
		PlayImmediateTone(400,200);
		//drive(N, 20, 300);
		//drive(AC, 50, 900);
		//drive(N, 50, 500);
		break;
	case 2:
		PlayImmediateTone(650,200);
		halt();
		drive(S, 10, 100);
		drive(CW, 30, 900);
		break;
	case 3:
		PlayImmediateTone(900,100);
		PlayImmediateTone(849,100);
		PlayImmediateTone(801,100);
		PlayImmediateTone(756,220);
		wait10Msec(500);
		//drive(S, 50, 600);
		//drive(FWD+25, 44, 1400);
		//wait1Msec(1000);
		//drive(FWD-25, 44, 1400);
		//drive(N, 20, 500);
		break;
	}
}

void mission_ramp(Alliance_t alliance)
{
	drive(N, 40, 2750);
}


task main() //*/*\*/*\*/*\*/*\*/*\*/*\*/*\*/
{
	//waitForStart();
	//StartTask(updateBearing);
	Alliance_t cur_alli = kAllianceRed;
	wait1Msec(500);


	int first_IR = SensorValue[IR_SEEK];
	drive(N, 40, 1200);
	int second_IR = SensorValue[IR_SEEK];
	writeDebugStreamLine("first: %i, second: %i", first_IR, second_IR);
	mission_monolith(cur_alli, 3);
	/*
	if (first_IR <= 3) {
		mission_monolith(cur_alli, 1);
	}
	else if (second_IR == 5) {
		mission_monolith(cur_alli, 3);
	}
	else {
		mission_monolith(cur_alli, 2);
	}
*/
	halt();
	PlayImmediateTone(200,200);
	wait1Msec(1000);
}
