#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     HTSPB,          sensorI2CCustom9V)
#pragma config(Sensor, S4,     IR_SEEK,        sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     DRIVE_SE,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     DRIVE_NE,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     LIFT,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     FEEDER,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     POPPER,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     DRIVE_SW,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C2_2,     DRIVE_NW,      tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S2_C3_1,    grab1,                tServoStandard)
#pragma config(Servo,  srvo_S2_C3_2,    grab2,                tServoStandard)
#pragma config(Servo,  srvo_S2_C3_3,    flip,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C3_4,    roof,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C3_5,    guides,               tServoStandard)
#pragma config(Servo,  srvo_S2_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#ifdef USING_CLION
#include "../headers/clion_1.h"
#endif
#define DEBUG_IR

#include "Joystickdriver.c"
#include "../headers/scaleJoy_1.h"
//#include "../headers/gyro_1.h"
#include "../headers/nav_5.h"
#include "../headers/helpers_1.h"

#include "../drivers/hitechnic-superpro.h"

//==================  Config Definitions  ==================
typedef enum
{
  kAllianceRed,
  kAllianceBlu
} Alliance_t;

typedef enum
{
  kPlanKick,
  kPlanRamp
} Plan_t;
#define DEF_PLAN_STRINGS const string Plan_s[] = {"Kick", "Ramp"};


#include "../headers/dialog_2.h"

void initialize_servos()
{
  servo[grab1] = 232;
  servo[grab2] = 16;
  servo[guides] = 0;
  servo[roof] = 180;
  servo[flip] = 0;
}

//==================  Missions  ==================
void mission_monolith(Alliance_t alliance, int monolith_position)
{
  writeDebugStreamLine("%i", monolith_position);

  switch (monolith_position) {
    case 1:
      drive_enc(N, 30, 2500);
      drive_enc(CW, 70, 1100);
      drive_enc(N, 70, 3000);
      drive(S, -2, 1200);
      break;
    case 2:
    	drive_enc(E, 20, 500);
      drive_enc(N, 55, 840);
      drive_enc(CW, 100, 1000);
      drive_enc(N, 100, 2800);
      drive(S, -2, 1200);
      break;
    case 3:
      drive_enc(CW, 50, 900);
      drive_enc(N, 50, 800);
      drive(CCW, 50, 900);
      drive_enc(N, 50, 600);
      drive(CW, 40, 1400);
      drive_enc(N, 58, 2000);
      //drive(S, -20, 1800);
      break;
  }
}

void mission_ramp(Alliance_t alliance)
{
  drive(S, 40, 500);
  drive(N, 1, 1000);
  drive(S, 2, 500);
  drive(N, 1, 100);
  drive(S, 20, 900);
/*
  servo[guides] = 255;
  wait1Msec(500);
  servo[guides] = 0;
*/
  drive(CCW, 40, 200);

  drive_enc(S, 20, 1300);
  drive(CCW, 40, 200);
  drive_enc(S, 15, 1000);
/*
  servo[grab1] = 8;
  servo[grab2] = 239;

  motor[LIFT] = 100;
  wait1Msec(6200);
  motor[LIFT] = 0;

  servo[flip] = 255;
  wait1Msec(750);
  servo[roof] = 60;
  wait1Msec(1000);

  servo[flip] = 245;
  wait1Msec(100);
  servo[flip] = 255;
  wait1Msec(50);
  servo[flip] = 245;
  wait1Msec(100);
  servo[flip] = 255;
  wait1Msec(50);
  servo[flip] = 245;
  wait1Msec(100);
  servo[flip] = 255;
  wait1Msec(1000);

  drive_enc(CCW, 100, 3000);
  drive_enc(S, 40, 800);

  servo[grab1] = 232; // release
  servo[grab2] = 16;

  drive_enc(N, 40, 800);
  drive_enc(CW, 100, 3700);
  drive(S, 20, 1200);

  servo[grab1] = 8; // grab
  servo[grab2] = 239;
  wait1Msec(1000);

  drive(N, 30, 500);
  drive(CCW, 100, 1400);
  drive(S, 30, 500);

  servo[grab1] = 232; // release
  servo[grab2] = 16;

  motor[LIFT] = 100;
  while (HTSPBreadIO(HTSPB, 0x01) != 1) {}
  motor[LIFT] = 0;
  */
}

//==================  Main Task  ==================
task main()
{
  HTSPBsetupIO(HTSPB, 0x10);

  Alliance_t cur_alli = kAllianceRed;
  Plan_t cur_plan = kPlanKick;
  int delay = 0;

  //dialog( &cur_alli, &cur_plan,  &delay); // Run Dialog for user input of parameters

  //initialize_servos();
  //  waitForStart();
  //  StartTask(updateBearing);

  wait1Msec(500);
  wait1Msec(delay*1000);

  switch (cur_plan) {
    case kPlanRamp: //================== Plan Ramp
      mission_ramp(cur_alli);
      break;


    case kPlanKick: //================== Plan Kick
      int first_IR = SensorValue[IR_SEEK];
      drive_enc(N, 20, 2000);
      int second_IR = SensorValue[IR_SEEK]; //157.56

      int monolith_position;
      if (first_IR <= 3) {
        monolith_position = 1;
      } else if (second_IR == 5) {
        monolith_position = 3;
      } else {
        monolith_position = 2;
      }
#ifdef DEBUG_IR
      writeDebugStreamLine("first: %i, second: %i", first_IR, second_IR);
      switch (monolith_position) {
      case 1:
        PlayImmediateTone(900, 300);
      break;
      case 2:
        PlayImmediateTone(650, 190);
        wait1Msec(10);
        PlayImmediateTone(650, 190);
        wait1Msec(10);
      break;
      case 3:
        PlayImmediateTone(400, 90);
        wait1Msec(10);
        PlayImmediateTone(400, 90);
        wait1Msec(10);
        PlayImmediateTone(400, 90);
        wait1Msec(10);
      }
      wait1Msec(2000);
#endif
      mission_monolith(cur_alli, monolith_position);
      drive_enc(CW, 80, 6000);
      /*
      servo[guides] = 255;
      wait1Msec(500);
      servo[guides] = 0;
      motor[LIFT] = 100;
      while (HTSPBreadIO(HTSPB, 0x01) != 1) {}*/
      motor[LIFT] = 0;
      break;
  }
  halt();

  //==================  Ending  ==================
  halt();
  PlayImmediateTone(200, 200);
  wait1Msec(1000);
}
