#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTServo,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     HTSPB,          sensorI2CCustom9V)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     DRIVE_SE,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     DRIVE_NE,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     TUBE,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     FEEDER,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     POPPER,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_2,     FORK,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     DRIVE_SW,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C2_2,     DRIVE_NW,      tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S2_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S2_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C3_3,    SPOUT,                tServoStandard)
#pragma config(Servo,  srvo_S2_C3_4,    ROOF,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C3_6,    FLAP,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C4_1,    GRAB1,                tServoStandard)
#pragma config(Servo,  srvo_S2_C4_2,    GRAB2,                tServoStandard)
#pragma config(Servo,  srvo_S2_C4_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C4_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C4_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C4_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../drivers/hitechnic-superpro.h"
#include "../headers/servoValues_1.h"

bool grab_lock = false;
bool grab_state = false;
task main()
{
	if (ServoValue[ROOF] != kRoofClosed) {
    servo[FLAP] = kFlapClosed;
    servo[ROOF] = kRoofClosed;
    wait1Msec(350);
  }
  servo[SPOUT] = 0;
  wait1Msec(1000);
  servo[ROOF] = kRoofOpen;
  wait1Msec(250);
  servo[FLAP] = kFlapOpen;
	while (true)
	{
		HTSPBsetupIO(HTSPB, 0x10);
		if (nNxtButtonPressed == 1) {
			motor[POPPER] = 100;
		}
		else {
			motor[POPPER] = 0;
		}
		if (HTSPBreadIO(HTSPB, 0x04) != 0 && HTSPBreadIO(HTSPB, 0x02) != 0) { // If limit switches are active
      if (!grab_lock) { // Unless auto-grabbing has already happened
        grab_lock = true; // Prevent auto-grabbing from occurring repeatedly
        grab_state = true; // Engage grabbers
      }
    } else { // If both limit switches have been released
      grab_lock = false; // Allow auto-grabbing to occur in the future
  	}
    if (grab_state == true) { //activate servos
      servo[GRAB1] = 215;
      servo[GRAB2] = 60;
    } else if (grab_state == false) {
      servo[GRAB1] = 55;
      servo[GRAB2] = 215;
    }
		if (nNxtButtonPressed == 2) {
				grab_state = false;
		}
	}
}
