#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S3,     HTSPB,          sensorI2CCustom9V)
#pragma config(Sensor, S4,     SMUX,           sensorI2CCustom)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     DRIVE_SE,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     DRIVE_NE,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     TUBE,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     FEEDER,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     POPPER,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_2,     FORK,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     DRIVE_SW,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C2_2,     DRIVE_NW,      tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S2_C3_1,    GRAB1,                tServoStandard)
#pragma config(Servo,  srvo_S2_C3_2,    GRAB2,                tServoStandard)
#pragma config(Servo,  srvo_S2_C3_3,    SPOUT,                tServoStandard)
#pragma config(Servo,  srvo_S2_C3_4,    ROOF,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C3_6,    FLAP,                 tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#ifdef USING_CLION
#include "../headers/clion_1.h"
#endif

#include "JoystickDriver.c"
#include "../headers/scaleJoy_1.h"
#include "../headers/helpers_1.h"
#include "../drivers/hitechnic-superpro.h"

//#include "../headers/liftControl_1.h"
bool grab_state = true;
int do_grab_change = 0;
float J1X1;
float J1Y1;
float J1X2;

float J2Y2;
short current_joystick;

task main()
{
  //nMotorEncoder[DRIVE_SE] = 0;
  // nMotorEncoder[DRIVE_SW] = 0;
  //StartTask(updateBearing);
  while (true) {
    getJoystickSettings(joystick);
    J1X1 = scaleJoy(joystick.joy1_x1);
    J1X2 = scaleJoy(joystick.joy1_x2);
    J1Y1 = scaleJoy(joystick.joy1_y1);


    J2Y2 = scaleJoy(joystick.joy2_y2);

    //nxtDisplayTextLine(2, "SE:%i, SW:%i", nMotorEncoder[DRIVE_SE], nMotorEncoder[DRIVE_SW]);

    //\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//
    action_joy1
    state bLB down
      motor[FEEDER] = 100;
    state bLT down
      motor[FEEDER] = -100;
    otherwise
      motor[FEEDER] = 0;
    end

    action_joy1
    state bRB down
    	motor[FORK] = 100;
    state bRT down
    	motor[FORK] = -100;
    otherwise
    	motor[FORK] = 0;
		end

    action_joy1 //grabbing roling goals
    state bA down
      if (do_grab_change) {
        // button was just pressed
        do_grab_change = false; //Set flag saying we've done it.
        grab_state = !grab_state;
// open all 210 closed 25 playing 100?
        // roof = 80
        // roof = 120
      }
    otherwise
      do_grab_change = true;
    end

    if (LEFT_GRABBER_SWITCH != 0 && RIGHT_GRABBER_SWITCH != 0 && do_grab_change == true) {
    	grab_state = true;
  }
  	if (joystick.joy1_Buttons == bB && do_grab_change == true) {
    	grab_state = true;
  }

    if (grab_state == true) {
          servo[GRAB1] = 215;
          servo[GRAB2] = 60;
        } else if (grab_state == false) {
          servo[GRAB1] = 55;
          servo[GRAB2] = 215;
        }

		//action_joy1
		//state bA down
		//	servo[GRAB1] = 55;
  //    servo[GRAB2] = 215;
		////otherwise
		////state bB down
		////	servo[GRAB1] = 215;
		////	servo[GRAB2] = 60;
  //  otherwise
		//	if (LEFT_GRABBER_SWITCH != 0 && RIGHT_GRABBER_SWITCH != 0) {
		//		do_grab_change = true;
		//		servo[GRAB1] = 215;
		//		servo[GRAB2] = 60;
		//	} else {
		//		servo[GRAB2] = 215;
		//		servo[GRAB1] = 55;
		//	}
		//end

    action_joy2 //adjusting ball dispenser
    state bRT down // close
    	servo[FLAP] = 25;
      servo[ROOF] = 255;
      wait1Msec(350);
      servo[SPOUT] = 0;
    state bRB down // open normal
      servo[SPOUT] = 255;
      wait1Msec(1000);
      servo[ROOF] = 127;
      wait1Msec(250);
      servo[FLAP] = 80;
    state bLB down // open for center
   		servo[FLAP] = 25;
      servo[ROOF] = 255;
      wait1Msec(350);
      servo[SPOUT] = 0;
    	wait1Msec(1000);
    	servo[ROOF] = 90;
    	wait1Msec(250);
    	servo[FLAP] = 210;
    end

    action_joy2 // run popper
    state bB down
      motor[POPPER] = 100;
    otherwise
      motor[POPPER] = 0;
    end

    action_joy2 // manually adjust roof
    state bY down
      servo[ROOF] = ServoValue[ROOF] - 2;
    state bA down
      servo[ROOF] = ServoValue[ROOF] + 2;
    end

    //\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//

    HTSPBsetupIO(HTSPB, 0x10);
    if (LIFT_SWITCH != 1) {
      nxtDisplayTextLine(1, "Magnet absent");
      //HTSPBwriteIO(HTSPB, 0x10);
    } else {
      nxtDisplayTextLine(1, "Magnet present");
      //HTSPBwriteIO(HTSPB, 0x00);
    }
    //StartTask(lift_control);
    if (LIFT_SWITCH != 1 || J2Y2 < 0) {
      motor[TUBE] = J2Y2;
    } else {
      motor[TUBE] = 0;
    }
    //nxtDisplayTextLine(1, "Height: %i", lift_height);
    //action_joy2
    // state bA down
    // 	height = 0;
    // end

    //if (height == 0 && (LIFT_SWITCH != 1)) {
    //	motor[LIFT] = 100;
    //} else {
    //	motor[LIFT] = 0;
    //	height = 1;
    //}
    motor[DRIVE_NE] = (J1Y1 + J1X1 - J1X2);
    motor[DRIVE_SE] = (J1Y1 - J1X1 - J1X2);
    motor[DRIVE_NW] = (J1Y1 - J1X1 + J1X2);
    motor[DRIVE_SW] = (J1Y1 + J1X1 + J1X2);
    writeDebugStreamLine("Y1:%g, X1:%g, X2:%g", J1Y1, J1X1, J1X2);
  }
}
