#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     DRIVE_SE,      tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     DRIVE_NE,      tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     LIFT,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     POPPER,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     FEEDER,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     DRIVE_NW,      tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S2_C2_2,     DRIVE_SW,      tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S2_C3_1,    grab1,                tServoStandard)
#pragma config(Servo,  srvo_S2_C3_2,    grab2,                tServoStandard)
#pragma config(Servo,  srvo_S2_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "../headers/scaleJoy_1.h"
#include "../headers/helpers_1.h"

float X1;
float Y1;
float X2;
float Y2;
short current_joystick;
task main()
{
  nMotorPIDSpeedCtrl[DRIVE_NE] = nMotorPIDSpeedCtrl[DRIVE_NW] = nMotorPIDSpeedCtrl[DRIVE_SE] = nMotorPIDSpeedCtrl[DRIVE_SW] = mtrSpeedReg;

  while (true) {
    getJoystickSettings(joystick);
    X1 = scaleJoy(joystick.joy1_x1);
    X2 = scaleJoy(joystick.joy1_x2);
    Y1 = scaleJoy(joystick.joy1_y1);
    Y2 = scaleJoy(joystick.joy2_y2);

    motor[LIFT] = Y2;
    motor[DRIVE_NE] = Y1 - X1 - X2;
    motor[DRIVE_SE] = Y1 + X1 - X2;
    motor[DRIVE_NW] = Y1 + X1 + X2;
    motor[DRIVE_SW] = Y1 - X1 + X2;

//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//

    action_joy1
    state bLB down
      motor[FEEDER] = 100;
    state bLT down
      motor[FEEDER] = -100;
    otherwise
      motor[FEEDER] = 0;
    end

    action_joy1
    state bY down
      servo[grab1] = 240;
      servo[grab2]=6;
    state bA down
      servo[grab1]=16;
      servo[grab2]=232;
    end

    action_joy1
    state bB down
      motor[POPPER] = 100;
    otherwise
      motor[POPPER] = 0;
    end
  }
}
