#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     LIGHTB,         sensorLightActive)
#pragma config(Sensor, S3,     LIGHTF,         sensorLightActive)
#pragma config(Sensor, S4,     IR_SEEK,        sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     WRIST,         tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     ARM,           tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     DRIVE_NW,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     DRIVE_NE,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     DRIVE_SE,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     DRIVE_SW,      tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    FLAG_ROT,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    AUTO_BLK,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    ULTRA_ROT,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an Tetrix robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "./nav_2.00.h"  //Our
#include "./scaleJoy.h"  //Our own code to scale joystick values.
//#include "./ultra_1.00.h"
/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
int offset;
int offset3;
int coolVal;
void lineFollow(int speed, float offset2)
{
	offset = offset2*(SensorValue[LIGHTF]-55);
		motor[DRIVE_NE] = speed+offset;
		motor[DRIVE_SE] = speed+offset;
		motor[DRIVE_NW] = speed-offset;
		motor[DRIVE_SW] = speed-offset;
}
void lineFollowBackwards(int speed, float offset2)
{
	offset = offset2*(SensorValue[LIGHTB]-55);
		motor[DRIVE_NE] = -speed-offset;
		motor[DRIVE_SE] = -speed-offset;
		motor[DRIVE_NW] = -speed+offset;
		motor[DRIVE_SW] = -speed+offset;
}
bool lineUp(){
	if (SensorValue[LIGHTB] >= 60 && SensorValue[LIGHTF] >= 60) {
		halt();
		return true;
	}
	else if (SensorValue[LIGHTB] < 60) {

		motor[DRIVE_SE] = 20;
	motor[DRIVE_SW] = -20;
	motor[DRIVE_NW] = -20;

	}
	else {
		motor[DRIVE_NE] = -20;
	motor[DRIVE_SW] = 20;
	motor[DRIVE_NW] = 20;

	}
	return false;
}


void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

servo[AUTO_BLK]=240;
servo[FLAG_ROT]=0;
return;
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////



task main()
{

	initializeRobot();
	nMotorEncoder[DRIVE_NW] = 0;
	while (nMotorEncoder[DRIVE_NW]<500) {
		drive(N,60,0);
	}
	while (SensorValue[LIGHTF]<57&&SensorValue[LIGHTB]<57){
		drive(E,30,0);
	}
	drive(W,30,180);
	nMotorEncoder[DRIVE_NW]=0;
	while (SensorValue[IR_SEEK]!=5) {
		if (SensorValue[IR_SEEK]>5 || SensorValue[IR_SEEK]==0) {
			lineFollow(15,1);
		}
		else {
			lineFollowBackwards(15,1);
		}
	}
	halt();
	//wait10Msec(100);
	//while (!lineUp()) {}
	//halt();
	//wait10Msec(100);
	coolVal=nMotorEncoder[DRIVE_NW];

	//if (coolVal<0){
	//	while((nMotorEncoder[DRIVE_NW]-coolVal)>-900){
	//		drive(S,25,0);
	//	}
	//}
	//else{
	if (coolVal<600){
		while((nMotorEncoder[DRIVE_NW]-coolVal)>-250){
			drive(S,25,0);
		}
	}
	else if (coolVal < 1000) {
		while((nMotorEncoder[DRIVE_NW]-coolVal)>-50){
			drive(S,25,0);
		}
	}
	else if (coolVal < 3500) {
		while((nMotorEncoder[DRIVE_NW]-coolVal)>-250){
			drive(S,25,0);
		}
	}
	else {
		while((nMotorEncoder[DRIVE_NW]-coolVal)>-250){
			drive(S,25,0);
		}
	}
	servoChangeRate[AUTO_BLK]=8;

	halt();

	servo[AUTO_BLK]=0;
	wait10Msec(85);
	servoChangeRate[AUTO_BLK]=10;
	servo[AUTO_BLK]=255;
	wait10Msec(40);

	while(nMotorEncoder[DRIVE_NW]<5900) {
		drive(N,60,0);
	}

	motor[DRIVE_NW] = 90;
	motor[DRIVE_SE] = 90;
	motor[DRIVE_NE] = -30;
	motor[DRIVE_SW] = -30;
	wait1Msec(1500);
	motor[DRIVE_NW] = 40;
	motor[DRIVE_SE] = 40;
	motor[DRIVE_NE] = -90;
	motor[DRIVE_SW] = -90;
	wait1Msec(1200);
	nMotorEncoder[DRIVE_NW]=0;
	while(nMotorEncoder[DRIVE_NW]>-3000) {
		drive(S,90,0);
	}
}
