#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S3,     IR_SENSOR,      sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     SONAR_SENSOR,   sensorSONAR)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     DRIVE_SW,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     DRIVE_SE,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     ARM_ROTATE,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     ARM,           tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     ARM_TILT,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     DRIVE_NE,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     DRIVE_NW,      tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C1_1,    AUTON_ROT,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "./scaleJoy.h"

void drive_forward(int speed) {
	motor[DRIVE_NE] = speed;
	motor[DRIVE_SE] = speed;
	motor[DRIVE_NW] = speed;
	motor[DRIVE_SW] = speed;
}

void drive_sideways(int speed) {
	motor[DRIVE_NE] = speed;
	motor[DRIVE_SE] = -speed;
	motor[DRIVE_NW] = -speed;
	motor[DRIVE_SW] = speed;
}

void turn(int degrees) {
		motor[DRIVE_NE] = 50;
		motor[DRIVE_SE] = 50;
		motor[DRIVE_NW] = -50;
		motor[DRIVE_SW] = -50;
		wait10Msec(degrees);
		motor[DRIVE_NE] = 0;
		motor[DRIVE_SE] = 0;
		motor[DRIVE_NW] = 0;
		motor[DRIVE_SW] = 0;

}

int x = 0;

task main() {
	while (SensorValue[IR_SENSOR]!=5) {
		if (SensorValue[IR_SENSOR]<5) {
			drive_forward(15);
			x++;
	}
	else {
			drive_forward(-15);
			x--;
		}
	}
	drive_forward(-10);
	wait10Msec(40);
	drive_forward(10);
	wait10Msec(50);
	while (SensorValue[SONAR_SENSOR]>30) {
		drive_sideways(30);
	}
	drive_forward(0);
	servo[AUTON_ROT]=255;
	wait10Msec(100);
	servo[AUTON_ROT]=0;
	wait10Msec(100);
	while (SensorValue[SONAR_SENSOR]<35) {
		drive_sideways(-30);
	}
	drive_forward(0);
	while (SensorValue[SONAR_SENSOR]<100) {
		drive_forward(15);
	}
	motor[DRIVE_NE] = 22;
	motor[DRIVE_SE] = 22;
	motor[DRIVE_NW] = -2;
	motor[DRIVE_SW] = -2;
	wait10Msec(270);
	drive_forward(30);
	wait10Msec(150);
	turn(90);
	drive_forward(30);
		wait10Msec(180);
	drive_forward(0);
	servo[AUTON_ROT]=200;
	wait10Msec(100);
}
