#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S4,     IR_SEEK,        sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     WRIST,         tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     ARM,           tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     DRIVE_NW,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     DRIVE_NE,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     DRIVE_SE,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     DRIVE_SW,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     FLAG,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     LIFT,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    FLAG_ROT,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    BLK_DROP,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    AUTO_BLK,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-sensormux.h"
#include "drivers/lego-light.h"
#include "drivers/hitechnic-colour-v2.h"

const tMUXSensor HTCOLOR1 = msensor_S3_1;
const tMUXSensor HTCOLOR2 = msensor_S3_2;

int red1 = 0;
int green1 = 0;
int blue1 = 0;
int hue1 = 0;
int saturation1 = 0;
int value1 = 0;

task main()
{

	while (true) {
		if (nNxtButtonPressed == 2) {
			writeDebugStreamLine("sensor1");
			HTCS2readRGB(HTCOLOR1, red1, green1, blue1);
			writeDebugStreamLine("r:%d, g:%d, b:%d",red1, green1, blue1);

				writeDebugStreamLine("sensor2");
			HTCS2readRGB(HTCOLOR2, red1, green1, blue1);
			writeDebugStreamLine("r:%d, g:%d, b:%d",red1, green1, blue1);

			//RGBtoHSV(red1,green1,blue1,hue1,saturation1,value1);

			//HTCS2readHSV(HTCOLOR1, hue, saturation, value);
			//writeDebugStreamLine("h:%d, s:%d, v:%d",hue1, saturation1, value1);
			wait1Msec(500);
		}

	}
}
