#pragma config(Hubs,  S4, HTMotor,  none,     none,     none)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LEFT,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RIGHT,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "./scaleJoy.h"

float Y1;
float X2;

task main()
{


	while(true){
		Y1 = scaleJoy(joystick.joy1_y1);
		X2 = scaleJoy(joystick.joy1_x2);
		motor[LEFT] = Y1-X2;
		motor[RIGHT]= Y1+X2;

	}
}
