#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     ULTRASONIC,     sensorSONAR)
#pragma config(Sensor, S4,     IR_SEEK,        sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     WRIST,         tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     ARM,           tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     DRIVE_NW,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     DRIVE_NE,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     DRIVE_SE,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     DRIVE_SW,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     FLAG,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     LIFT,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    FLAG_ROT,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    AUTO_BLK,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    ULTRA_ROT,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an Tetrix robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "./nav_2.00.h"  //Our
#include "./scaleJoy.h"  //Our own code to scale joystick values.
#include "./ultra_1.00.h"
/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

servo[AUTO_BLK]=240;

return;
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

int stuff = 0;
short encoderVal;
short coolVal=0;
bool sawFront = false;
bool sawFrontSide = false;
bool sawFrontSide2 = false;
int ultraValue = 0;
int ultraValue2 = 0;
int ultraValue3 = 0;

bool codeCheck1 = false;
bool codeCheck2 = false;
bool codeCheck3 = false;
bool codeCheck4 = false;

void zig1F() {
	motor[DRIVE_NW] = 50;
	motor[DRIVE_SE] = 50;
	motor[DRIVE_NE] = -20;
	motor[DRIVE_SW] = -20;
	wait1Msec(1000);
	halt();
}

void zig2F() {
	motor[DRIVE_NW] = 50;
	motor[DRIVE_SE] = 50;
	motor[DRIVE_NE] = -20;
	motor[DRIVE_SW] = -20;
	wait1Msec(1000);
	halt();
	drive(E,60,1250);
	drive(S,80,2000);
}

void zig1FB() {
	motor[DRIVE_NW] = -50;
	motor[DRIVE_SE] = -50;
	motor[DRIVE_NE] = 20;
	motor[DRIVE_SW] = 20;
	wait1Msec(1000);
	halt();
}

void zig1B() {
	motor[DRIVE_NW] = 20;
	motor[DRIVE_SE] = 20;
	motor[DRIVE_NE] = -50;
	motor[DRIVE_SW] = -50;
	wait1Msec(2000);
	halt();
	drive(E,60,1700);
	drive(N,80,1600);
}

short driveBack(short coolVal) {
	while (coolVal>1000) {
		drive(S,20,0);
		coolVal = encoderVal + nMotorEncoder[DRIVE_NW];
	}
	halt();
	return coolVal;
}

short driveForwardC(short coolVal) {
	while (coolVal<7050) {
		codeCheck2 = true;
		drive(N,20,0);
		coolVal = encoderVal + nMotorEncoder[DRIVE_NW];
	}
	halt();
	return coolVal;
}


task main()
{
	initializeRobot();
	moveServo(RIGHTSIDE); //move servo to front of robot
	resetCounter(); //reset counter for checking ultrasonic

	//move arm and wrist to ideal position for autonomous
	servo[FLAG_ROT]=0;

	motor[ARM]= -20;
	wait10Msec(30);
	motor[ARM]=0;
	motor[WRIST] = 20;
	wait10Msec(10);
	motor[WRIST] = 0;

	nMotorEncoder[DRIVE_NW]=0;

	while (SensorValue[IR_SEEK]!=5) {
		if (SensorValue[IR_SEEK]>5 || SensorValue[IR_SEEK]==0) {
			drive(N,20,0);
		}
		else {
			drive(S,20,0);
		}
	}

	drive(S,20,275);

	encoderVal=nMotorEncoder[DRIVE_NW];

	if (encoderVal<=2600) {
		drive(E,30,800);
	}
	else {
		drive(E,30,1600);
	}
	drive(W,30,175);

	halt();

	servo[AUTO_BLK]=0;
	wait10Msec(70);
	servo[AUTO_BLK]=255;
	wait10Msec(70);

	drive(W,30,500);
	drive(CCW,40,175);

	nMotorEncoder[DRIVE_NW] = 0;
	resetCounter();
	//drive forwards
	coolVal = driveForwardC(coolVal);
	zig1F();
	zig2F();
}
