#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     DRIVE_SE,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     DRIVE_SW,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     DRIVE_NW,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     DRIVE_NE,      tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define button1	   0x01
#define button2	   0x02
#define button3	   0x04
#define button4	   0x08
#define button5	   0x10
#define button6	   0x20
#define button7	   0x40
#define button8	   0x80
#define button9	  0x100
#define button10  0x200
#define button11  0x800
#define button12 0x1000

const bool bLogarithmicScale = true;
const bool kMaximumPowerLevel = 100;  // Adjust to set max power level to be used.

int scaleJoy(int &nJoy1, int nMaxValue = kMaximumPowerLevel)
{
	//
	// This function scales the joystick settings to the appropriate range for
	// controlling a NXT motor.
	//
	// Joystick values range from -128 to +127.
	// Speed/power settings for NXT motors range from -100 to +100
	//
	// The physical range of motion of a joystick is quite small and it is sometimes
	// hard to control slow speeds. So another capability of this program to apply
	// a "logarithmic" scale to the joystick settings.
	//
	static const int nLogScale[17] =
	{
		1,	 5,	  9,   10,
		12,	 15,  18,  24,
		30,	 36,  43,  50,
		60,	 72,  85, 100,
		100
	};
	int nScaled;

	nScaled = nJoy1;
	if (bLogarithmicScale)
	{
		nScaled /= 8;
		if (nScaled >= 0)
			nScaled = nLogScale[nScaled];
		else
			nScaled = - nLogScale[ - nScaled];
	}
	nScaled *= nMaxValue;
	nScaled /= 100;
	return nScaled;
}


int NEval;
int NWval;
int SEval;
int SWval;
float angle;
float tanValue;
int X1;
float Y1;
float X2;
int threshold = 4;
task main()
{
	while (true) {
		getJoystickSettings(joystick);
		motor[left]=100;
		motor[right]=100;
		X1 = scaleJoy(joystick.joy1_x1);
		X2 = scaleJoy(joystick.joy1_x2);
		Y1 = scaleJoy(joystick.joy1_y1);
		if(X1 > 0 && Y1 > 0) {
			angle = atan(Y1/X1);
			tanValue = sqrt(pow(X1,2)+pow(Y1,2))*sin(angle-0.7853981)/cos(angle-0.7853981);

			NEval = tanValue;
			SWval = tanValue;
			SEval = sqrt(pow(X1,2)+pow(Y1,2));
			NWval = sqrt(pow(X1,2)+pow(Y1,2));
		}
		else if(-X1 > 0 && -Y1 > 0) {
			angle = atan(Y1/X1);
			tanValue = -sqrt(pow(X1,2)+pow(Y1,2))*sin(angle-0.7853981)/cos(angle-0.7853981);
			NEval = tanValue;
			SWval = tanValue;
			SEval = -sqrt(pow(X1,2)+pow(Y1,2));
			NWval = -sqrt(pow(X1,2)+pow(Y1,2));
		}
		else if(-X1 > 0 && Y1 > 0) {
			angle = atan(-Y1/X1);
			tanValue = sqrt(pow(X1,2)+pow(Y1,2))*sin(angle-0.7853981)/cos(angle-0.7853981);
			SEval = tanValue;
			NWval = tanValue;
			NEval = sqrt(pow(X1,2)+pow(Y1,2));
			SWval = sqrt(pow(X1,2)+pow(Y1,2));
		}
		else if(X1 > 0 && -Y1 > 0) {
			angle = atan(-Y1/X1);
			tanValue = -sqrt(pow(X1,2)+pow(Y1,2))*sin(angle-0.7853981)/cos(angle-0.7853981);
			SEval = tanValue;
			NWval = tanValue;
			NEval = -sqrt(pow(X1,2)+pow(Y1,2));
			SWval = -sqrt(pow(X1,2)+pow(Y1,2));
		}
		else {
				NEval= X2;
				NWval= -X2;
				SEval= X2;
				SWval= -X2;
		}

		if (NEval<threshold && NEval>-threshold){
			if (X2>threshold || X2<-threshold) {
				NEval=-X2;
			}
			else {
				NEval=0;
			}
		}
		if (SEval<threshold && SEval>-threshold){
			if (X2>threshold || X2<-threshold) {
				SEval=-X2;
			}
			else {
				SEval=0;
			}
		}
		if (NWval<threshold && NWval>-threshold){
			if (X2>threshold || X2<-threshold) {
				NWval=X2;
			}
			else {
				NWval=0;
			}
		}
		if (SWval<threshold && SWval>-threshold){
			if (X2>threshold || X2<-threshold) {
				SWval=X2;
			}
			else {
				SWval=0;
			}
		}
		motor[DRIVE_NE] = NEval;
		motor[DRIVE_SE] = SEval;
		motor[DRIVE_NW] = NWval;
		motor[DRIVE_SW] = SWval;

	}


}
