#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     IR_SENSOR,      sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     DRIVE_SW,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     DRIVE_SE,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     ARM_ROTATE,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     FLAG,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     ARM,           tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     ARM_TILT,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     DRIVE_NE,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     DRIVE_NW,      tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C1_1,    AUTON_ROT,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    LIFT,                 tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "./scaleJoy.h"

float X1;
float Y1;
float X2;
float X3;
float Y2;

task main()
{
		while (true) {
			servo[AUTON_ROT]=255;
		getJoystickSettings(joystick);
		nMotorPIDSpeedCtrl[ARM] = mtrSpeedReg;
		X1 = scaleJoy(joystick.joy1_x1);
		X2 = scaleJoy(joystick.joy1_x2);
		Y1 = scaleJoy(joystick.joy1_y1);
		X3 = scaleJoy(joystick.joy2_x2);
		Y2 = scaleJoy(joystick.joy2_y1);

		motor[ARM_ROTATE]= -X3 *0.5;

		motor[ARM] = -Y2 *0.5;

			if (joystick.joy2_Buttons & button6){ //RB
			motor[ARM_TILT]=20;
		}
		else if (joystick.joy2_Buttons & button8){ //RT
			motor[ARM_TILT]=-20;
		}
		else{
			motor[ARM_TILT]=0;
		}

			if (joystick.joy2_Buttons & button5){ //LB
			motor[left]=100;
			motor[right]=100;
		}
		else	if (joystick.joy2_Buttons & button7){ //LT
			motor[left]=-100;
			motor[right]=-100;
		}
		else{
			motor[left]=0;
			motor[right]=0;
		}

		if (joystick.joy2_Buttons & button2){ //A
			motor[FLAG]=100;
		}
		else	if (joystick.joy2_Buttons & button4){ //Y
			motor[FLAG]=-100;
		}
		else{
			motor[FLAG]=0;
		}

			if (joystick.joy2_Buttons & button1){ //X
			servo[LIFT]=255;
		}
		else	if (joystick.joy2_Buttons & button3){ //B
			servo[LIFT]=0;
		}
		else{
			servo[LIFT]=127;
		}

		motor[DRIVE_NE] = Y1-X1-X2;
		motor[DRIVE_SE] = Y1+X1-X2;
		motor[DRIVE_NW] = Y1+X1+X2;
		motor[DRIVE_SW] = Y1-X1+X2;

	}
}
