#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     DRIVE_SE,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     DRIVE_SW,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     DRIVE_NW,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     DRIVE_NE,      tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define button1	   0x01
#define button2	   0x02
#define button3	   0x04
#define button4	   0x08
#define button5	   0x10
#define button6	   0x20
#define button7	   0x40
#define button8	   0x80
#define button9	  0x100
#define button10  0x200
#define button11  0x800
#define button12 0x1000

int threshold = 5;

int scaleJoy(int &nJoy1) {
	int nScaled;
	nScaled = nJoy1;
	if (abs(nScaled)>threshold) {
		if (abs(nScaled)>115) {
			return 100*abs(nScaled)/nScaled;
		}
		else {
			return 0.0075614*pow(nScaled,2)*abs(nScaled)/nScaled;
		}
	}
	else {
		return 0;
	}
}


float X1;
float Y1;
float X2;

task main()
{
	while (true) {
		getJoystickSettings(joystick);
		motor[left]=100;
		motor[right]=100;

		X1 = scaleJoy(joystick.joy1_x1);
		X2 = scaleJoy(joystick.joy1_x2);
		Y1 = scaleJoy(joystick.joy1_y1);

		motor[DRIVE_NE] = Y1-X1-X2;
		motor[DRIVE_SE] = Y1+X1-X2;
		motor[DRIVE_NW] = Y1+X1+X2;
		motor[DRIVE_SW] = Y1-X1+X2;

	}


}
