#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     DRIVE_SE,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     DRIVE_SW,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     DRIVE_NW,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     DRIVE_NE,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     FLAG,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_1,     ARM,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     ARM_ROTATE,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     motorN,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     motorO,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_1,     motorP,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_2,     motorQ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C4_1,     motorR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C4_2,     motorS,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define button1	   0x01
#define button2	   0x02
#define button3	   0x04
#define button4	   0x08
#define button5	   0x10
#define button6	   0x20
#define button7	   0x40
#define button8	   0x80
#define button9	  0x100
#define button10  0x200
#define button11  0x800
#define button12 0x1000

const bool bLogarithmicScale = true;
const bool kMaximumPowerLevel = 100;  // Adjust to set max power level to be used.

int scaleJoy(int &nJoy1, int nMaxValue = kMaximumPowerLevel)
{
	//
	// This function scales the joystick settings to the appropriate range for
	// controlling a NXT motor.
	//
	// Joystick values range from -128 to +127.
	// Speed/power settings for NXT motors range from -100 to +100
	//
	// The physical range of motion of a joystick is quite small and it is sometimes
	// hard to control slow speeds. So another capability of this program to apply
	// a "logarithmic" scale to the joystick settings.
	//
	static const int nLogScale[17] =
	{
		0,	 5,	  9,   10,
		12,	 15,  18,  24,
		30,	 36,  43,  50,
		60,	 72,  85, 100,
		100
	};
	int nScaled;

	nScaled = nJoy1;
	if (bLogarithmicScale)
	{
		nScaled /= 8;
		if (nScaled >= 0)
			nScaled = nLogScale[nScaled];
		else
			nScaled = - nLogScale[ - nScaled];
	}
	nScaled *= nMaxValue;
	nScaled /= 100;
	return nScaled;
}

float X1;
float Y1;
float X2;

task main()
{
	while (true) {
		getJoystickSettings(joystick);




		X1 = scaleJoy(joystick.joy1_x1);
		X2 = scaleJoy(joystick.joy1_x2);
		Y1 = scaleJoy(joystick.joy1_y1);

		if (joystick.joy1_Buttons & button5){
		motor[FLAG]=100;
		}
		else{
		motor[FLAG]=0;
		}
		if (joystick.joy1_Buttons & button3){
		motor[ARM_ROTATE]=30;
		}
		else if (joystick.joy1_Buttons & button1){
		motor[ARM_ROTATE]=-30;
		}
		else{
		motor[ARM_ROTATE]=0;
		}
		if (joystick.joy1_Buttons & button2){
		motor[ARM]=55;
		}
		else if (joystick.joy1_Buttons & button4){
			motor[ARM]=-100;
		}
		else{
		motor[ARM]=0;
		}

		motor[DRIVE_NE] = Y1-X1-X2;
		motor[DRIVE_SE] = Y1+X1-X2;
		motor[DRIVE_NW] = Y1+X1+X2;
		motor[DRIVE_SW] = Y1-X1+X2;

	}


}
