#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     DRIVE_SE,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     DRIVE_SW,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     DRIVE_NW,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     DRIVE_NE,      tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define button1	   0x01
#define button2	   0x02
#define button3	   0x04
#define button4	   0x08
#define button5	   0x10
#define button6	   0x20
#define button7	   0x40
#define button8	   0x80
#define button9	  0x100
#define button10  0x200
#define button11  0x800
#define button12 0x1000



const bool bLogarithmicScale = true;
const bool kMaximumPowerLevel = 100;  // Adjust to set max power level to be used.
int threshold = 5;
int maxControl = 115;

int scaleJoy(int &nJoy1)
{
	//
	// This function scales the joystick settings to the appropriate range for
	// controlling a NXT motor.
	//
	// Joystick values range from -128 to +127.
	// Speed/power settings for NXT motors range from -100 to +100
	//
	// The physical range of motion of a joystick is quite small and it is sometimes
	// hard to control slow speeds. So another capability of this program to apply
	// a "logarithmic" scale to the joystick settings.
	//

	int nScaled;

	nScaled = nJoy1;
	if (nScaled>0) {
		if (nScaled>maxControl) {
			return 100;
		}
		else {
			return pow(1.04085,nScaled);
			}
		}
	else if (nScaled<0) {
		if (nScaled<-maxControl) {
			return -100;
		}
		else {
			return -pow(1.04085,-nScaled);
		}
	}
	else {
		return 0;
	}
}


int NEval;
int NWval;
int SEval;
int SWval;
float angle;
float tanValue;
task main()
{
	while (true) {
		getJoystickSettings(joystick);
		motor[left]=100;
		motor[right]=100;
		if(abs(joystick.joy1_y1)>threshold && abs(joystick.joy1_x1)<threshold) {
			NEval = scaleJoy(joystick.joy1_y1);
			NWval = scaleJoy(joystick.joy1_y1);
			SEval = scaleJoy(joystick.joy1_y1);
			SWval = scaleJoy(joystick.joy1_y1);
		}
		else if(abs(joystick.joy1_x1)>threshold && abs(joystick.joy1_y1)<threshold) {
			NEval= -(scaleJoy(joystick.joy1_x1));
			NWval= (scaleJoy(joystick.joy1_x1));
			SEval= (scaleJoy(joystick.joy1_x1));
			SWval= -(scaleJoy(joystick.joy1_x1));
		}
		else if(scaleJoy(joystick.joy1_x1) > 0 && scaleJoy(joystick.joy1_y1) > 0) {
			angle = atan((float)joystick.joy1_y1/(float)joystick.joy1_x1);
			tanValue = 1.4142*sqrt(pow(joystick.joy1_x1,2)+pow(joystick.joy1_y1,2))*sin((float)angle-0.7853981)/cos((float)angle-0.7853981);
			NEval = tanValue;
			SWval = tanValue;
			SEval = 1.4142*sqrt(pow(joystick.joy1_x1,2)+pow(joystick.joy1_y1,2));
			NWval = 1.4142*sqrt(pow(joystick.joy1_x1,2)+pow(joystick.joy1_y1,2));
		}
		else if(-scaleJoy(joystick.joy1_x1) > threshold && -scaleJoy(joystick.joy1_y1) > threshold) {
			angle = atan((float)joystick.joy1_y1/(float)joystick.joy1_x1);
			tanValue = -1.4142*sqrt(pow(joystick.joy1_x1,2)+pow(joystick.joy1_y1,2))*sin((float)angle-0.7853981)/cos((float)angle-0.7853981);
			NEval = tanValue;
			SWval = tanValue;
			SEval = -1.4142*sqrt(pow(joystick.joy1_x1,2)+pow(joystick.joy1_y1,2));
			NWval = -1.4142*sqrt(pow(joystick.joy1_x1,2)+pow(joystick.joy1_y1,2));
		}
		else if(-scaleJoy(joystick.joy1_x1) > threshold && scaleJoy(joystick.joy1_y1) > threshold) {
			angle = atan((float)joystick.joy1_y1/(float)joystick.joy1_x1);
			tanValue = 1.4142*sqrt(pow(joystick.joy1_x1,2)+pow(joystick.joy1_y1,2))*sin((float)angle-0.7853981)/cos((float)angle-0.7853981);
			SEval = tanValue;
			NWval = tanValue;
			NEval = 1.4142*sqrt(pow(joystick.joy1_x1,2)+pow(joystick.joy1_y1,2));
			SWval = 1.4142*sqrt(pow(joystick.joy1_x1,2)+pow(joystick.joy1_y1,2));
		}
		else if(scaleJoy(joystick.joy1_x1) > threshold && -scaleJoy(joystick.joy1_y1) > threshold) {
			angle = atan((float)joystick.joy1_y1/(float)joystick.joy1_x1);
			tanValue = -1.4142*sqrt(pow(joystick.joy1_x1,2)+pow(joystick.joy1_y1,2))*sin((float)angle-0.7853981)/cos((float)angle-0.7853981);
			SEval = tanValue;
			NWval = tanValue;
			NEval = -1.4142*sqrt(pow(joystick.joy1_x1,2)+pow(joystick.joy1_y1,2));
			SWval = -1.4142*sqrt(pow(joystick.joy1_x1,2)+pow(joystick.joy1_y1,2));
		}
		else {
				NEval= (scaleJoy(joystick.joy1_x2));
				NWval= -(scaleJoy(joystick.joy1_x2));
				SEval= (scaleJoy(joystick.joy1_x2));
				SWval=  -(scaleJoy(joystick.joy1_x2));
	}

		if (NEval<threshold){
			NEval=0;
		}
		if (SEval<threshold){
			SEval=0;
		}
		if (NWval<threshold){
			NWval=0;
		}
		if (SWval<threshold){
			SWval=0;
		}

		//Remote Control Commands
		motor[DRIVE_NE] = NEval;
		motor[DRIVE_SE] = SEval;
		motor[DRIVE_NW] = NWval;
		motor[DRIVE_SW] = SWval;

	}


}
