#pragma config(Hubs,	S4, HTMotor,	none,			none,			none)
#pragma config(Sensor, S4,		 ,							 sensorI2CMuxController)
#pragma config(Motor,	 mtr_S4_C1_1,			PID,					 tmotorTetrix, PIDControl)
#pragma config(Motor,	 mtr_S4_C1_2,			NORM,					 tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//

#include "JoystickDriver.c"
#include "./scaleJoy.h"

task main()
{
	while (true) {
		//if(joystick.joy1_Buttons & button1) {
		//	motor[PID]=20;
		//}
		//else {
		//	motor[PID]=0;
		//}
		//nMotorEncoderTarget[PID]=20;
		motor[PID]=20;
		//Sleep(20000);
	}
}
